// Generated by dart2js (NullSafetyMode.sound, csp, deferred-serialization, intern-composite-values), the Dart to JavaScript compiler version: 3.1.3.
((s, d, e) => {
  s[d] = s[d] || {};
  s[d][e] = s[d][e] || [];
  s[d][e].push({p: "main.clients.dart.js_2", e: "beginPart"});
})(self, "$__dart_deferred_initializers__", "eventLog");
$__dart_deferred_initializers__.current = function(hunkHelpers, init, holdersList, $) {
  var A = {StatelessComponent: function StatelessComponent() {
    }},
  B;
  A = hunkHelpers.updateHolder(holdersList[5], A);
  B = holdersList[0];
  A.StatelessComponent.prototype = {};
  var typesOffset = hunkHelpers.updateTypes([]);
  (function inheritance() {
    var _inherit = hunkHelpers.inherit;
    _inherit(A.StatelessComponent, B.Component);
  })();
  B._Universe_addRules(init.typeUniverse, JSON.parse('{"StatelessComponent":{"Component":[]}}'));
};
;
((d, h) => {
  d[h] = d.current;
  d.eventLog.push({p: "main.clients.dart.js_2", e: "endPart", h: h});
})($__dart_deferred_initializers__, "rff4x3b+GnoB9TN1JC0TUY7C/yw=");
;
//# sourceMappingURL=main.clients.dart.js_2.part.js.map
