// Generated by dart2js (NullSafetyMode.sound, csp, deferred-serialization, intern-composite-values), the Dart to JavaScript compiler version: 3.1.3.
((s, d, e) => {
  s[d] = s[d] || {};
  s[d][e] = s[d][e] || [];
  s[d][e].push({p: "main.clients.dart.js_1", e: "beginPart"});
})(self, "$__dart_deferred_initializers__", "eventLog");
$__dart_deferred_initializers__.current = function(hunkHelpers, init, holdersList, $) {
  var A = {Index: function Index(t0) {
      this.key = t0;
    }, _$Index: function _$Index() {
    }, _Index_StatelessComponent__$Index: function _Index_StatelessComponent__$Index() {
    },
    getComponentForParams0(p) {
      return new A.Index(null);
    }
  },
  C, B;
  A = hunkHelpers.updateHolder(holdersList[3], A);
  C = holdersList[5];
  B = holdersList[0];
  A.Index.prototype = {};
  A._$Index.prototype = {};
  A._Index_StatelessComponent__$Index.prototype = {};
  var typesOffset = hunkHelpers.updateTypes([]);
  (function inheritance() {
    var _mixin = hunkHelpers.mixin,
      _inherit = hunkHelpers.inherit;
    _inherit(A._Index_StatelessComponent__$Index, C.StatelessComponent);
    _inherit(A.Index, A._Index_StatelessComponent__$Index);
    _inherit(A._$Index, B.Object);
    _mixin(A._Index_StatelessComponent__$Index, A._$Index);
  })();
  B._Universe_addRules(init.typeUniverse, JSON.parse('{"Index":{"Component":[]}}'));
};
;
((d, h) => {
  d[h] = d.current;
  d.eventLog.push({p: "main.clients.dart.js_1", e: "endPart", h: h});
})($__dart_deferred_initializers__, "YzGHYpBT242JJ4u8BE6ZHU3hIwY=");
;
//# sourceMappingURL=main.clients.dart.js_1.part.js.map
