// Generated by dart2js (NullSafetyMode.sound, csp, deferred-serialization, intern-composite-values), the Dart to JavaScript compiler version: 3.1.3.
((s, d, e) => {
  s[d] = s[d] || {};
  s[d][e] = s[d][e] || [];
  s[d][e].push({p: "main.clients.dart.js_3", e: "beginPart"});
})(self, "$__dart_deferred_initializers__", "eventLog");
$__dart_deferred_initializers__.current = function(hunkHelpers, init, holdersList, $) {
  var A = {Hello: function Hello(t0) {
      this.key = t0;
    }, _$Hello: function _$Hello() {
    }, _Hello_StatelessComponent__$Hello: function _Hello_StatelessComponent__$Hello() {
    },
    getComponentForParams(p) {
      return new A.Hello(null);
    }
  },
  C, B;
  A = hunkHelpers.updateHolder(holdersList[4], A);
  C = holdersList[5];
  B = holdersList[0];
  A.Hello.prototype = {};
  A._$Hello.prototype = {};
  A._Hello_StatelessComponent__$Hello.prototype = {};
  var typesOffset = hunkHelpers.updateTypes([]);
  (function inheritance() {
    var _mixin = hunkHelpers.mixin,
      _inherit = hunkHelpers.inherit;
    _inherit(A._Hello_StatelessComponent__$Hello, C.StatelessComponent);
    _inherit(A.Hello, A._Hello_StatelessComponent__$Hello);
    _inherit(A._$Hello, B.Object);
    _mixin(A._Hello_StatelessComponent__$Hello, A._$Hello);
  })();
  B._Universe_addRules(init.typeUniverse, JSON.parse('{"Hello":{"Component":[]}}'));
};
;
((d, h) => {
  d[h] = d.current;
  d.eventLog.push({p: "main.clients.dart.js_3", e: "endPart", h: h});
})($__dart_deferred_initializers__, "AuaJ04yjWkxOC8AANZzSIw2Lx1o=");
;
//# sourceMappingURL=main.clients.dart.js_3.part.js.map
