name: sanihaq.github.io
description: my github site using jaspr.
version: 0.0.1

publish_to: none

authors:
  - "sanihaq"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  jaspr: ^0.9.1
  jaspr_router: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.4
  jaspr_builder: ^0.9.1
  lints: ^2.1.0
  jaspr_tailwind: ^0.1.0

jaspr:
  uses-ssr: true
