name: Build Site

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: build jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version
      - run: dart pub global activate jaspr_cli
      - run: jaspr --version
      - run: jaspr generate
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: build/jaspr
      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
